apiVersion: factotum.io/v1alpha1
kind: NamespaceConfig
metadata:
  labels:
    app.kubernetes.io/name: factotum
    app.kubernetes.io/managed-by: kustomize
  name: namespaceconfig-sample
spec:
  selector:
    namespaceSelector:
      kubernetes.io/metadata.name: "kube.*"
  annotations:
    factotum: applied
  labels:
    factotum: applied
  namespaces:
    - name: facto1
    - name: facto2
