apiVersion: factotum.io/v1alpha1
kind: NodeConfig
metadata:
  labels:
    app.kubernetes.io/name: factotum
    app.kubernetes.io/managed-by: kustomize
  name: nodeconfig-sample
spec:
  selector:
    nodeSelector:
      kubernetes.io/hostname: kind-worker.*
  annotations:
    factotum: applied
  labels:
    factotum: applied
    node-role.kubernetes.io/worker: ""
  taints:
  - key: factotum
    value:  tainted
    effect: NoSchedule
