version: 2
before:
  hooks:
    - go mod tidy
builds:
  - 
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X github.com/rjbrown57/factotum/cmd.version={{.Version}}"
dockers:
  - image_templates:
    - ghcr.io/rjbrown57/factotum
    - ghcr.io/rjbrown57/factotum:{{ .Tag }}
archives:
  - formats: ['binary']
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: rjbrown57
    name: factotum
