---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
  labels:
    {{- include "factotum.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - factotum.io
  resources:
  - namespaceconfigs
  - nodeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - factotum.io
  resources:
  - namespaceconfigs/finalizers
  - nodeconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - factotum.io
  resources:
  - namespaceconfigs/status
  - nodeconfigs/status
  verbs:
  - get
  - patch
  - update
