# permissions for end users to view namespaceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: factotum
    app.kubernetes.io/managed-by: kustomize
  name: namespaceconfig-viewer-role
rules:
- apiGroups:
  - factotum.io
  resources:
  - namespaceconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - factotum.io
  resources:
  - namespaceconfigs/status
  verbs:
  - get
