---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - factotum.io
  resources:
  - nodeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - factotum.io
  resources:
  - nodeconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - factotum.io
  resources:
  - nodeconfigs/status
  verbs:
  - get
  - patch
  - update
