apiVersion: factotum.io/v1alpha1
kind: NodeConfig
metadata:
  labels:
    app.kubernetes.io/name: factotum
    app.kubernetes.io/managed-by: kustomize
  name: nodeconfig-sample
spec:
  annotations:
    factotum: applied
  labels:
    factotum: applied
  taints:
  - key: factotum
    value:  tainted
    effect: NoSchedule
